### ISSUE TITLE
Hi - question I can't seem to establish

### ISSUE THREAD

**Issue by ouverz** [piskvorky/data_science_python#2]
Hi, I really liked your tutorial!
I can't quite get my head around the way in which the pipeline works. Say I run 

``` python
pipeline = Pipeline([ ('tfidf', vectoriser), ('classifier', MultinomialNB() )])
```

Does the pipeline function essentially tokenise the corpus, create a tf-idf matrix, develop an NB model and fit the data? 

Then when I run: 

``` python
scores = cross_val_score(pipeline, train_data, train_label, cv=5, scoring='accuracy, n_jobs=-1,)
```

Then I print `scores`, this is the accuracy of what then? I don't see where the prediction on the test data takes place?

Thanks

**Comment by piskvorky** [comment]
Thanks :)

The Pipeline is not a function, it's an object. It follows a similar API to the rest of scikit-learn: `fit()`, `transform()` etc. These method of Pipeline are called internally, inside the `cross_val_score()`.

Regarding cross-validation: the dataset you pass in is split into 5 pieces (folds, `cv=5`). The pipeline is trained ("fitted") on 4 of them, evaluated on the 5th. Then another 4 pieces are taken, and evaluated on the 5th etc. A total of five trainings/evaluations take place, so you get back different accuracy numbers, as an array.

It is common to then inspect the spread of these five scores, to see how stable the classifier is. If the standard deviation is small, you can perhaps represent the total performance of the pipeline as a simple average of these five numbers, `mean(scores)`.

See also this [tutorial on crossvalidation](http://scikit-learn.org/stable/modules/cross_validation.html).

**Comment by RishabGoel** [comment]
I agree with piskvorky. Just an addition, pipelines ar an efficient internal implementaion to spees up the process. It is a kind of directed graph that helps us to acieve the same text processing as done in the previous sections. 
When you run cross_val_score (for cv=10), it prints out the accuray score 10 times indicating that, the algorithm ran 10 times, everytime holding different x% of the data.
